
export type ProtocolPhase = {
  id: string;
  title: string;
  range: string;
  description: string;
};

export type ProtocolDay = {
  day: number;
  phase: 1 | 2 | 3;
  title: string;
  objective: string;
  mainAction: string;
  howTo: string[];
  observe: string[];
  avoid: string[];
  checklist: string[];
  recordPrompt: string;
  isApplicationDay?: boolean;
  requiresPhoto?: boolean;
  evaluationType?: "first" | "intermediate" | "final";
};

export const PROTOCOL_PHASES: ProtocolPhase[] = [
  {
    id: "fase-1",
    title: "FASE 1 — INICIAR, OBSERVAR E COMPREENDER",
    range: "Dias 1 a 7",
    description: "Conhecer a orquídea, registrar o ponto de partida, iniciar o Método de 2 Passos e aprender a observar raízes, folhas, rega, vaso e substrato.",
  },
  {
    id: "fase-2",
    title: "FASE 2 — COMPARAR, MANTER E AJUSTAR",
    range: "Dias 8 a 14",
    description: "Comparar os registros, acompanhar os pontos do diagnóstico, manter uma rotina simples e corrigir somente o que for necessário.",
  },
  {
    id: "fase-3",
    title: "FASE 3 — CONSOLIDAR, AVALIAR E MANTER",
    range: "Dias 15 a 21",
    description: "Reconhecer os cuidados que funcionaram, acompanhar a evolução e definir uma rotina de manutenção depois do plano.",
  },
];

export const PROTOCOL_DAYS: ProtocolDay[] = [
  {
    day: 1,
    phase: 1,
    title: "DIAGNÓSTICO E PRIMEIRA APLICAÇÃO",
    objective: "Registrar o ponto de partida e iniciar o Método de 2 Passos.",
    mainAction: "Revisar o diagnóstico, registrar a foto inicial e realizar a primeira aplicação.",
    howTo: [
      "Confirmar os dados da orquídea.",
      "Registrar uma fotografia da planta inteira.",
      "Observar raízes, folhas, brotos, vaso e substrato.",
      "Revisar os principais pontos do diagnóstico.",
      "Realizar a aplicação somente depois da fotografia e da observação inicial.",
    ],
    observe: [
      "Aparência das raízes.",
      "Firmeza e coloração das folhas.",
      "Brotos ou hastes.",
      "Umidade e drenagem.",
      "Estabilidade da planta no vaso.",
    ],
    avoid: [
      "Fazer várias mudanças ao mesmo tempo.",
      "Fotografar somente depois da aplicação.",
      "Encharcar raízes ou substrato.",
      "Aplicar diretamente nas flores.",
    ],
    checklist: [
      "Revisei meu diagnóstico",
      "Registrei a fotografia inicial",
      "Observei raízes e folhas",
      "Conferi vaso, substrato e drenagem",
      "Realizei o Passo 1 — Enraizar",
      "Realizei o Passo 2 — Nutrir",
      "Registrei a aplicação",
    ],
    recordPrompt: "Como minha orquídea está no início do plano?",
    requiresPhoto: true,
    isApplicationDay: true,
  },
  {
    day: 2,
    phase: 1,
    title: "OBSERVAR A RESPOSTA INICIAL",
    objective: "Acompanhar a planta sem realizar novas intervenções.",
    mainAction: "Observar raízes, folhas, substrato e ambiente.",
    howTo: [
      "Comparar a planta com a fotografia inicial.",
      "Registrar apenas mudanças que realmente possam ser observadas.",
      "Manter a planta em local estável.",
    ],
    observe: [
      "Firmeza das folhas.",
      "Aparência das raízes.",
      "Tempo de secagem.",
      "Manchas novas.",
      "Reação inesperada depois da aplicação.",
    ],
    avoid: [
      "Repetir a aplicação.",
      "Regar automaticamente.",
      "Mudar a planta de lugar sem necessidade.",
      "Fazer várias correções simultâneas.",
    ],
    checklist: [
      "Observei as raízes",
      "Observei as folhas",
      "Verifiquei a umidade",
      "Mantive a planta em local estável",
      "Registrei qualquer alteração",
    ],
    recordPrompt: "O que mudou desde o Dia 1?",
  },
  {
    day: 3,
    phase: 1,
    title: "ENTENDER A REGA",
    objective: "Criar critérios para decidir quando regar.",
    mainAction: "Avaliar a umidade antes de realizar qualquer rega.",
    howTo: [
      "Observar as raízes.",
      "Verificar o peso do vaso.",
      "Avaliar a superfície e o interior visível do substrato.",
      "Conferir se existe água acumulada.",
    ],
    observe: [
      "Substrato ainda úmido.",
      "Raízes verdes ou prateadas.",
      "Peso do vaso.",
      "Água acumulada.",
      "Secagem rápida ou lenta.",
    ],
    avoid: [
      "Regar apenas por calendário.",
      "Manter água no cachepot.",
      "Considerar somente a superfície do substrato.",
      "Aumentar a frequência sem observar a planta.",
    ],
    checklist: [
      "Observei a umidade",
      "Conferi as raízes",
      "Verifiquei o peso do vaso",
      "Retirei água acumulada, quando necessário",
      "Decidi sobre a rega pela observação",
    ],
    recordPrompt: "Qual critério usei para decidir sobre a rega?",
  },
  {
    day: 4,
    phase: 1,
    title: "AVALIAR VASO E SUBSTRATO",
    objective: "Conferir drenagem, estabilidade e aeração.",
    mainAction: "Observar o vaso e o substrato sem desmontar a planta.",
    howTo: [
      "Conferir os furos do vaso.",
      "Observar o escoamento.",
      "Verificar a compactação.",
      "Avaliar cheiro e estabilidade.",
    ],
    observe: [
      "Substrato compacto.",
      "Material se desfazendo.",
      "Mau cheiro.",
      "Água acumulada.",
      "Planta solta.",
      "Secagem muito lenta.",
    ],
    avoid: [
      "Trocar o substrato por impulso.",
      "Retirar a planta do vaso apenas para concluir a tarefa.",
      "Manipular excessivamente as raízes.",
    ],
    checklist: [
      "Conferi os furos do vaso",
      "Observei o escoamento",
      "Avaliei o substrato",
      "Verifiquei se a planta está firme",
      "Registrei a condição encontrada",
    ],
    recordPrompt: "Como estão o vaso, a drenagem e o substrato?",
  },
  {
    day: 5,
    phase: 1,
    title: "OBSERVAR AS RAÍZES",
    objective: "Acompanhar a condição do sistema radicular.",
    mainAction: "Observar as raízes aéreas e as raízes visíveis no vaso.",
    howTo: [
      "Observar sem retirar a planta.",
      "Comparar com a fotografia inicial.",
      "Verificar cor, firmeza e pontas novas.",
    ],
    observe: [
      "Firmeza.",
      "Cor.",
      "Pontas novas.",
      "Partes secas.",
      "Áreas escuras.",
      "Raízes moles.",
      "Mau cheiro.",
    ],
    avoid: [
      "Cortar raízes apenas pela cor.",
      "Retirar a planta do vaso sem necessidade.",
      "Manipular pontas novas.",
    ],
    checklist: [
      "Observei a firmeza",
      "Observei a coloração",
      "Procurei pontas novas",
      "Verifiquei áreas secas ou escuras",
      "Registrei o principal sinal",
    ],
    recordPrompt: "Qual foi o principal sinal observado nas raízes?",
  },
  {
    day: 6,
    phase: 1,
    title: "OBSERVAR FOLHAS, BROTOS E HASTES",
    objective: "Acompanhar sinais visíveis de vigor.",
    mainAction: "Comparar folhas antigas, folhas novas, brotos e hastes com o início do plano.",
    howTo: [
      "Observar folhas antigas e novas separadamente.",
      "Verificar firmeza, coloração e manchas.",
      "Procurar novos crescimentos.",
    ],
    observe: [
      "Firmeza.",
      "Enrugamento.",
      "Amarelamento.",
      "Manchas.",
      "Folha nova.",
      "Brotação.",
      "Haste em desenvolvimento.",
    ],
    avoid: [
      "Avaliar a evolução somente pela presença de flores.",
      "Manipular brotações.",
      "Fazer mudanças bruscas de luz.",
    ],
    checklist: [
      "Observei a firmeza das folhas",
      "Observei a coloração",
      "Verifiquei manchas",
      "Procurei folhas novas, brotos ou hastes",
      "Registrei o principal sinal",
    ],
    recordPrompt: "O que observei nas folhas, brotos ou hastes?",
  },
  {
    day: 7,
    phase: 1,
    title: "PRIMEIRA AVALIAÇÃO E SEGUNDA APLICAÇÃO",
    objective: "Comparar a primeira semana e realizar a segunda aplicação semanal.",
    mainAction: "Fotografar, avaliar e somente depois aplicar.",
    howTo: [
      "Registrar a fotografia antes da aplicação.",
      "Comparar com o Dia 1.",
      "Preencher a avaliação.",
      "Conferir as condições da planta.",
      "Realizar o Método de 2 Passos.",
      "Registrar a aplicação.",
    ],
    observe: [
      "Mudanças nas raízes.",
      "Firmeza das folhas.",
      "Brotos.",
      "Manchas.",
      "Tempo de secagem.",
      "Estabilidade da planta.",
    ],
    avoid: [
      "Aplicar antes da fotografia e da avaliação.",
      "Avaliar apenas a presença de flores.",
      "Repetir o registro da aplicação por engano.",
      "Encharcar a planta.",
    ],
    checklist: [
      "Registrei a foto do Dia 7",
      "Comparei com o Dia 1",
      "Registrei o que melhorou",
      "Registrei o que permaneceu igual",
      "Registrei o que precisa de atenção",
      "Realizei os dois passos",
      "Registrei a aplicação",
    ],
    recordPrompt: "O que melhorou, permaneceu igual ou ainda precisa de atenção?",
    requiresPhoto: true,
    isApplicationDay: true,
    evaluationType: "first",
  },
  {
    day: 8,
    phase: 2,
    title: "OBSERVAR APÓS A SEGUNDA APLICAÇÃO",
    objective: "Acompanhar a planta sem realizar novas intervenções.",
    mainAction: "Observar raízes, folhas, umidade e substrato.",
    howTo: [
      "Comparar com o registro do Dia 7.",
      "Manter a rotina estável.",
      "Registrar reações inesperadas.",
    ],
    observe: [
      "Raízes.",
      "Folhas.",
      "Umidade.",
      "Tempo de secagem.",
      "Sinais inesperados.",
    ],
    avoid: [
      "Repetir a aplicação.",
      "Introduzir outros produtos.",
      "Alterar vários cuidados.",
    ],
    checklist: [
      "Observei as raízes",
      "Observei as folhas",
      "Verifiquei a umidade",
      "Mantive a rotina estável",
      "Registrei qualquer reação",
    ],
    recordPrompt: "Como a planta está depois da segunda aplicação?",
  },
  {
    day: 9,
    phase: 2,
    title: "REVISAR O DIAGNÓSTICO",
    objective: "Retomar os pontos identificados no início.",
    mainAction: "Comparar o diagnóstico com os registros da primeira semana.",
    howTo: [
      "Revisar as prioridades.",
      "Identificar sinais que continuam presentes.",
      "Observar o que agora pode ser avaliado.",
      "Escolher até três pontos para acompanhar.",
    ],
    observe: [
      "Sinais presentes.",
      "Sinais que desapareceram.",
      "Novas informações.",
      "Pontos ainda não observados.",
    ],
    avoid: [
      "Tratar um resultado antigo como atual quando as respostas mudaram.",
      "Tentar corrigir tudo ao mesmo tempo.",
      "Ignorar sinais de piora.",
    ],
    checklist: [
      "Revisei o diagnóstico",
      "Conferi os pontos prioritários",
      "Comparei com os registros",
      "Escolhi até três pontos para acompanhar",
      "Atualizei minhas observações",
    ],
    recordPrompt: "Quais pontos do diagnóstico continuarei acompanhando?",
  },
  {
    day: 10,
    phase: 2,
    title: "REVISAR A ROTINA DE REGA",
    objective: "Verificar se a rega está sendo decidida pela observação.",
    mainAction: "Revisar as últimas regas e os critérios utilizados.",
    howTo: [
      "Conferir as anotações.",
      "Verificar umidade e peso do vaso.",
      "Observar água acumulada.",
      "Identificar regas realizadas sem necessidade.",
    ],
    observe: [
      "Rega automática.",
      "Excesso de água.",
      "Acúmulo no cachepot.",
      "Mudanças frequentes de rotina.",
    ],
    avoid: [
      "Regar somente porque chegou determinado dia.",
      "Compensar uma rega esquecida com excesso.",
      "Alterar vários critérios ao mesmo tempo.",
    ],
    checklist: [
      "Revisei as últimas regas",
      "Identifiquei o critério mais útil",
      "Conferi água acumulada",
      "Escolhi um hábito para manter",
      "Escolhi um erro para evitar",
    ],
    recordPrompt: "Qual hábito de rega será mantido?",
  },
  {
    day: 11,
    phase: 2,
    title: "COMPARAR AS RAÍZES",
    objective: "Verificar mudanças em relação aos Dias 1 e 5.",
    mainAction: "Comparar as raízes com registros anteriores.",
    howTo: [
      "Observar as mesmas regiões.",
      "Comparar firmeza, cor e pontas.",
      "Registrar melhora, estabilidade ou piora.",
    ],
    observe: [
      "Pontas novas.",
      "Firmeza.",
      "Áreas escuras.",
      "Raízes secas.",
      "Raízes moles.",
      "Odor.",
    ],
    avoid: [
      "Esperar mudanças expressivas em poucos dias.",
      "Forçar a visualização.",
      "Confundir mudança de cor pela umidade com alteração permanente.",
    ],
    checklist: [
      "Comparei com o Dia 1",
      "Comparei com o Dia 5",
      "Observei firmeza",
      "Procurei pontas novas",
      "Registrei a evolução",
    ],
    recordPrompt: "As raízes melhoraram, permaneceram iguais ou pioraram?",
  },
  {
    day: 12,
    phase: 2,
    title: "COMPARAR FOLHAS E BROTAÇÕES",
    objective: "Identificar mudanças visíveis na parte aérea.",
    mainAction: "Comparar folhas, brotos e hastes com os registros anteriores.",
    howTo: [
      "Observar folhas antigas e novas.",
      "Comparar manchas.",
      "Procurar novos crescimentos.",
      "Registrar mudanças reais.",
    ],
    observe: [
      "Firmeza.",
      "Coloração.",
      "Evolução de manchas.",
      "Folhas novas.",
      "Brotos.",
      "Hastes.",
    ],
    avoid: [
      "Usar apenas a floração como indicador.",
      "Ignorar manchas aumentando.",
      "Manipular novos crescimentos.",
    ],
    checklist: [
      "Comparei a firmeza",
      "Comparei a coloração",
      "Observei manchas",
      "Procurei novos crescimentos",
      "Registrei a mudança principal",
    ],
    recordPrompt: "Qual mudança observei nas folhas, brotos ou hastes?",
  },
  {
    day: 13,
    phase: 2,
    title: "REVISAR AMBIENTE E CUIDADOS",
    objective: "Identificar excessos e mudanças desnecessárias.",
    mainAction: "Revisar luz, ventilação, local da planta, regas e produtos utilizados.",
    howTo: [
      "Conferir se a planta permaneceu em local estável.",
      "Verificar exposição ao sol.",
      "Avaliar circulação de ar.",
      "Revisar os produtos utilizados.",
    ],
    observe: [
      "Sol forte.",
      "Ambiente muito escuro.",
      "Falta de ventilação.",
      "Mudanças frequentes.",
      "Uso simultâneo de produtos.",
    ],
    avoid: [
      "Misturar vários produtos.",
      "Mudar a planta frequentemente.",
      "Compensar aplicação esquecida com excesso.",
      "Fazer várias correções simultâneas.",
    ],
    checklist: [
      "Revisei a luminosidade",
      "Revisei a ventilação",
      "Conferi a estabilidade do local",
      "Revisei os produtos utilizados",
      "Escolhi um ajuste necessário",
    ],
    recordPrompt: "Qual cuidado está funcionando e qual ajuste ainda é necessário?",
  },
  {
    day: 14,
    phase: 2,
    title: "AVALIAÇÃO INTERMEDIÁRIA E TERCEIRA APLICAÇÃO",
    objective: "Comparar as duas primeiras semanas e realizar a terceira aplicação.",
    mainAction: "Fotografar, avaliar e somente depois aplicar.",
    howTo: [
      "Registrar a fotografia antes da aplicação.",
      "Comparar com os Dias 1 e 7.",
      "Preencher a avaliação intermediária.",
      "Conferir raízes, folhas, umidade e drenagem.",
      "Realizar os dois passos.",
      "Registrar a aplicação.",
    ],
    observe: [
      "Evolução das raízes.",
      "Firmeza e cor das folhas.",
      "Brotações.",
      "Manchas.",
      "Estabilidade do substrato.",
      "Consistência da rotina.",
    ],
    avoid: [
      "Aplicar antes da avaliação.",
      "Considerar ausência de flores como falta de evolução.",
      "Ignorar sinais de piora.",
      "Repetir o registro.",
    ],
    checklist: [
      "Registrei a foto do Dia 14",
      "Comparei com os Dias 1 e 7",
      "Registrei a melhor evolução",
      "Registrei o principal ponto pendente",
      "Realizei os dois passos",
      "Registrei a aplicação",
    ],
    recordPrompt: "Qual foi the melhor evolução e o principal ponto ainda pendente?",
    requiresPhoto: true,
    isApplicationDay: true,
    evaluationType: "intermediate",
  },
  {
    day: 15,
    phase: 3,
    title: "OBSERVAR APÓS A TERCEIRA APLICAÇÃO",
    objective: "Acompanhar a planta sem novas intervenções.",
    mainAction: "Observar a condição geral.",
    howTo: [
      "Comparar com a avaliação do Dia 14.",
      "Manter local e rotina estáveis.",
      "Registrar qualquer reação inesperada.",
    ],
    observe: [
      "Raízes.",
      "Folhas.",
      "Brotos.",
      "Umidade.",
      "Tempo de secagem.",
      "Reações inesperadas.",
    ],
    avoid: [
      "Repetir a aplicação.",
      "Mudar a planta de local.",
      "Introduzir outros produtos.",
    ],
    checklist: [
      "Observei raízes e folhas",
      "Verifiquei a umidade",
      "Observei brotos ou hastes",
      "Mantive a rotina",
      "Registrei o sinal mais importante",
    ],
    recordPrompt: "Qual foi o sinal mais importante observado hoje?",
  },
  {
    day: 16,
    phase: 3,
    title: "IDENTIFICAR O QUE ESTÁ FUNCIONANDO",
    objective: "Reconhecer os cuidados mais úteis.",
    mainAction: "Revisar as anotações e escolher hábitos que devem continuar.",
    howTo: [
      "Comparar ações com sinais observados.",
      "Identificar o melhor critério de rega.",
      "Avaliar estabilidade do local.",
      "Reconhecer melhorias na rotina.",
    ],
    observe: [
      "Melhor critério de rega.",
      "Local mais estável.",
      "Melhor drenagem.",
      "Redução de erros.",
      "Sinais favoráveis.",
    ],
    avoid: [
      "Atribuir toda mudança a uma única ação.",
      "Criar expectativa de floração imediata.",
      "Introduzir novos produtos antes do final.",
    ],
    checklist: [
      "Revisei as anotações",
      "Identifiquei o cuidado mais útil",
      "Identifiquei um erro que deixei de cometer",
      "Escolhi dois cuidados para manter",
    ],
    recordPrompt: "Quais dois cuidados serão mantidos?",
  },
  {
    day: 17,
    phase: 3,
    title: "COMPARAR AS RAÍZES",
    objective: "Acompanhar o sistema radicular antes da avaliação final.",
    mainAction: "Comparar as raízes com os registros anteriores.",
    howTo: [
      "Observar as mesmas regiões.",
      "Comparar firmeza, cor e pontas.",
      "Registrar a mudança mais relevante.",
    ],
    observe: [
      "Pontas novas.",
      "Firmeza.",
      "Coloração.",
      "Partes secas.",
      "Áreas escuras.",
      "Odor.",
    ],
    avoid: [
      "Manipular raízes novas.",
      "Retirar a planta sem necessidade.",
      "Fazer conclusões por um único sinal.",
    ],
    checklist: [
      "Observei la firmeza",
      "Observei a coloração",
      "Procurei pontas novas",
      "Comparei com os registros anteriores",
      "Registrei a mudança principal",
    ],
    recordPrompt: "Qual foi a principal mudança observada nas raízes?",
  },
  {
    day: 18,
    phase: 3,
    title: "COMPARAR FOLHAS, BROTOS E HASTES",
    objective: "Verificar a evolução da parte aérea.",
    mainAction: "Comparar a parte aérea com os registros anteriores.",
    howTo: [
      "Observar folhas antigas e novas.",
      "Comparar brotos e hastes.",
      "Verificar manchas e amarelamento.",
    ],
    observe: [
      "Firmeza.",
      "Folhas novas.",
      "Brotos.",
      "Hastes.",
      "Manchas.",
      "Amarelamento.",
    ],
    avoid: [
      "Avaliar sucesso somente pelas flores.",
      "Fazer mudanças bruscas antes da foto final.",
      "Manipular novos crescimentos.",
    ],
    checklist: [
      "Observei as folhas",
      "Procurei brotos",
      "Observei hastes",
      "Verifiquei manchas",
      "Registrei a mudança principal",
    ],
    recordPrompt: "Qual foi a principal mudança observada na parte aérea?",
  },
  {
    day: 19,
    phase: 3,
    title: "CRIAR A ROTINA DE MANUTENÇÃO",
    objective: "Planejar os cuidados depois do protocolo.",
    mainAction: "Definir uma rotina simples e possível de manter.",
    howTo: [
      "Definir como decidir sobre a rega.",
      "Escolher o local principal da planta.",
      "Definir quais sinais acompanhar.",
      "Planejar novas fotografias.",
      "Manter a aplicação semanal.",
    ],
    observe: [
      "Hábitos que funcionaram.",
      "Cuidados difíceis de manter.",
      "Pontos que ainda precisam de acompanhamento.",
    ],
    avoid: [
      "Criar um calendário rígido de rega.",
      "Misturar vários produtos.",
      "Abandonar os registros.",
      "Alterar vários fatores ao mesmo tempo.",
    ],
    checklist: [
      "Defini como decidirei sobre a rega",
      "Defini o local principal",
      "Escolhi os sinais que continuarei acompanhando",
      "Planejei novos registros",
      "Defini minha rotina semanal",
    ],
    recordPrompt: "Como será minha rotina de manutenção?",
  },
  {
    day: 20,
    phase: 3,
    title: "PREPARAR A COMPARAÇÃO FINAL",
    objective: "Organizar os registros antes do encerramento.",
    mainAction: "Revisar fotografias, aplicações, diagnóstico e anotações.",
    howTo: [
      "Revisar fotos dos Dias 1, 7 e 14.",
      "Conferir aplicações registradas.",
      "Revisar o diagnóstico.",
      "Escolher três aspectos para comparar.",
    ],
    observe: [
      "Mudanças consistentes.",
      "Pontos sem alteração.",
      "Sinais que pioraram.",
      "Cuidados mantidos.",
      "Lacunas nos registros.",
    ],
    avoid: [
      "Fazer uma nova intervenção.",
      "Mudar o local da planta.",
      "Escolher somente os registros mais favoráveis.",
      "Considerar apenas flores.",
    ],
    checklist: [
      "Revisei as fotos",
      "Revisei as aplicações",
      "Revisei o diagnóstico",
      "Revisei minhas anotações",
      "Escolhi três aspectos para comparar",
    ],
    recordPrompt: "Quais três aspectos compararei no Dia 21?",
  },
  {
    day: 21,
    phase: 3,
    title: "AVALIAÇÃO FINAL E QUARTA APLICAÇÃO",
    objective: "Comparar o antes e depois, concluir o plano e iniciar a manutenção semanal.",
    mainAction: "Fotografar, avaliar, concluir o plano e somente depois aplicar.",
    howTo: [
      "Fotografar antes da aplicação.",
      "Comparar com os Dias 1, 7 e 14.",
      "Preencher a avaliação final.",
      "Definir os cuidados que serão mantidos.",
      "Concluir o plano.",
      "Realizar o Método de 2 Passos.",
      "Registrar a quarta aplicação.",
    ],
    observe: [
      "Raízes.",
      "Folhas.",
      "Brotos e hastes.",
      "Estabilidade da planta.",
      "Comportamento do substrato.",
      "Consistência da rotina.",
      "Sinais de atenção.",
    ],
    avoid: [
      "Aplicar antes da fotografia e avaliação.",
      "Avaliar sucesso somente pela floração.",
      "Ignorar deterioração.",
      "Alterar registros antigos.",
      "Repetir a aplicação.",
    ],
    checklist: [
      "Registrei a foto final",
      "Comparei os quatro marcos",
      "Preenchi a avaliação final",
      "Defini os cuidados de manutenção",
      "Concluí o plano",
      "Realizei os dois passos",
      "Registrei a quarta aplicação",
    ],
    recordPrompt: "O que melhorou, o que permaneceu igual e o que ainda precisa de atenção?",
    requiresPhoto: true,
    isApplicationDay: true,
    evaluationType: "final",
  },
];

export const APPLICATION_DAYS = [1, 7, 14, 21];
export const PHOTO_DAYS = [1, 7, 14, 21];

export function normalizeProtocolDay(day: number): number {
  if (day < 1) return 1;
  if (day > 21) return 21;
  return Math.floor(day);
}

export function getProtocolDay(day: number): ProtocolDay {
  const normalized = normalizeProtocolDay(day);
  return PROTOCOL_DAYS[normalized - 1];
}

export function getProtocolPhase(day: number): ProtocolPhase {
  const dayInfo = getProtocolDay(day);
  return PROTOCOL_PHASES[dayInfo.phase - 1];
}
