/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Protocolo21DiasRouteImport } from './routes/protocolo-21-dias'
import { Route as IndexRouteImport } from './routes/index'

const Protocolo21DiasRoute = Protocolo21DiasRouteImport.update({
  id: '/protocolo-21-dias',
  path: '/protocolo-21-dias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/protocolo-21-dias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/protocolo-21-dias'
  id: '__root__' | '/' | '/protocolo-21-dias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Protocolo21DiasRoute: typeof Protocolo21DiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocolo-21-dias': {
      id: '/protocolo-21-dias'
      path: '/protocolo-21-dias'
      fullPath: '/protocolo-21-dias'
      preLoaderRoute: typeof Protocolo21DiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Protocolo21DiasRoute: Protocolo21DiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
