/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Protocolo21DiasRouteImport } from './routes/protocolo-21-dias'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as IndexRouteImport } from './routes/index'

const Protocolo21DiasRoute = Protocolo21DiasRouteImport.update({
  id: '/protocolo-21-dias',
  path: '/protocolo-21-dias',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bem-vindo' | '/protocolo-21-dias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bem-vindo' | '/protocolo-21-dias'
  id: '__root__' | '/' | '/bem-vindo' | '/protocolo-21-dias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BemVindoRoute: typeof BemVindoRoute
  Protocolo21DiasRoute: typeof Protocolo21DiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocolo-21-dias': {
      id: '/protocolo-21-dias'
      path: '/protocolo-21-dias'
      fullPath: '/protocolo-21-dias'
      preLoaderRoute: typeof Protocolo21DiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BemVindoRoute: BemVindoRoute,
  Protocolo21DiasRoute: Protocolo21DiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
